package br.com.tide;

public enum PlayerState {

	STAND, ATTACK, BEING_HIT, DEAD, LOWER, 
	LOOK_UP, LOOK_DOWN, STAND_DOWN,
	WALK_RIGHT, WALK_LEFT, WALK_UP, WALK_DOWN, 
	TURN_RIGHT, TURN_LEFT, WALK_FORWARD, WALK_BACKWARD,
	JUMP, FALL, SPECIAL_ATTACK,	
	
}
